### PR TITLE
Add tests Github action

### PR DESCRIPTION
**Pull request by pedropregueiro**

### CODE REVIEW

**Comment by pedropregueiro** [comment]
@kalaspuff could use your eyes on this 🙏 

I tried a few different ways to pass environment variables into the gh actions, but it seems like it's not picking it up, no matter the place I try to add them. Right now, I have some repository secrets set and try to fetch them on the pytest step with `${{ secrets.<var_name> }}`.

**Comment by kalaspuff** [comment]
@pedropregueiro I wonder if it could be that the `addnab/docker-run-action@v3` action is actually running the command within its own container, and maybe the environment values aren't passed into that container. (see: https://github.com/addnab/docker-run-action/blob/main/entrypoint.sh#L11).

Maybe we should try to use another action that does similar tasks but works with envs, or if there isn't one, just fork the `addnab/docker-run-action@v3` action to add support fort it directly. Seems like a use-case which could do good overall.

**Comment by pedropregueiro** [comment]
Thanks @kalaspuff, I'll have a look at this again later this week!

**Comment by pedropregueiro** [comment]
@kalaspuff this is now working as expected, though I've stopped using docker (and docker-related actions). Linters and tests are all running <2mins which seems pretty good. We can even speed that up later w/ `pytest-xdist`, if needed.

Apart from consistency between environments[1], was there any other reason to use docker here that I might be missing?

[1] - This is actually not super relevant today as we're not using a dockerized production environment either.

**Pull request merged**
